GET http://localhost:3001/api/notes/

###

POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content": "for some people this is just a game",
    "important": false,
    "userId": "67e4428a6b7ff0316396e43c"
}

###
PUT http://localhost:3001/api/notes/67e05e728eac89258b017c55
Content-Type: application/json

{
    "content": "This is a nice note you have, be a shame if somebody...",
    "important": false
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "alice",
    "name": "Alice",
    "password": "alphaBetaGamma"
}

###
GET http://localhost:3001/api/users 