GET http://localhost:3001/info

###
DELETE http:localhost:3001/api/persons/3

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "mogambo johnny",
    "number": "09829881739"
}

###
PUT http://localhost:3001/api/persons/67e0552e796d09b34ecb4657
Content-Type: application/json

{
    "name": "Alia Bhatt",
    "number": "08-12-357819"
}
