POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "pain in head",
    "author": "Alice",
    "url": "https://www.dostoyevsky.com",
    "likes": 47
}

###
GET http://localhost:3001/api/blogs